#!/usr/bin/perl                                                                                                                                                                  

use strict;
use warnings;

use App::Prove;

my $app = App::Prove->new;
$app->process_args(@ARGV);
$app->lib('lib');
$app->run;

__END__
